// Generated by https://quicktype.io

export interface FavoriteResponse {
    OneListGetByCardIdResult: Favorite[];
}

export interface Favorite {
    Id:              string;
    CardId:          string;
    CardLinks:       CardLink[];
    CreateDate:      string;
    Description:     string;
    ExternalType:    number;
    Items:           Item[];
    ListType:        number;
    PointAmount:     number;
    PublishedOffers: any[];
    ShippingAmount:  number;
    StoreId:         string;
    TotalAmount:     number;
    TotalDiscAmount: number;
    TotalNetAmount:  number;
    TotalTaxAmount:  number;
}

 interface CardLink {
    CardId: string;
    Name:   string;
    Owner:  boolean;
    Status: number;
}

export interface Item {
    Id:                       string;
    Amount:                   number;
    BarcodeId:                string;
    CreateDate:               string;
    Detail:                   string;
    DiscountAmount:           number;
    DiscountPercent:          number;
    DisplayOrderId:           number;
    Image:                    Partial<Image>;
    ItemDescription:          string;
    ItemId:                   string;
    NetAmount:                number;
    NetPrice:                 number;
    OnelistItemDiscounts:     any[];
    Price:                    number;
    Quantity:                 number;
    TaxAmount:                number;
    UnitOfMeasureDescription: null;
    UnitOfMeasureId:          string;
    VariantDescription:       string;
    VariantId:                string;
    VariantRegistration:      VariantRegistration;
}

export interface Image {
    Id:           string;
    AvgColor:     string;
    DisplayOrder: number;
    Format:       string;
    Image:        string;
    ImgSize:      ImgSize;
    LoadFromFile: boolean;
    Location:     string;
    LocationType: number;
}

export interface ImgSize {
    Height:           number;
    UseMinHorVerSize: boolean;
    Width:            number;
}

export interface VariantRegistration {
    Id:            string;
    Dimension1:    string;
    Dimension2:    string;
    Dimension3:    string;
    Dimension4:    string;
    Dimension5:    string;
    Dimension6:    string;
    FrameworkCode: string;
    Images:        any[];
    ItemId:        string;
}
