// Generated by https://quicktype.io

export interface StoresResponse {
    StoresGetAllResult: Store[];
}

export interface Store {
    Id: string;
    Address: Address;
    CultureName: null;
    Currency: Currency;
    DefaultCustomer: null;
    Description: string;
    Distance: number;
    FunctionalityProfileId: null;
    Images: Image[];
    IsClickAndCollect: boolean;
    Latitude: number;
    Longitude: number;
    Phone: string;
    StoreHours: any[];
    StoreServices: any[];
    TaxGroupId: string;
    UseDefaultCustomer: null;
}

export interface Address {
    Address1: string;
    Address2: string;
    ApartmentNo: string;
    Area: string;
    CellPhoneNumber: null;
    City: string;
    Country: string;
    FloorNo: string;
    HouseNo: null;
    Id: string;
    LineNO: number;
    Number: string;
    PhoneNumber: null;
    PostCode: string;
    StateProvinceRegion: string;
    Street: string;
    Type: number;
}

export interface Currency {
    __type: Type;
    Id: string;
    AmountRoundingMethod: number;
    Culture: string;
    DecimalPlaces: number;
    DecimalSeparator: string;
    Description: string;
    Postfix: string;
    Prefix: string;
    RoundOffAmount: number;
    RoundOffSales: number;
    SaleRoundingMethod: number;
    Symbol: string;
    ThousandSeparator: string;
}

export enum Type {
    UnknownCurrencyHTTPLsretailCOMLSOmniServiceBase2017 = "UnknownCurrency:http://lsretail.com/LSOmniService/Base/2017",
}

export interface Image {
    Id: string;
    AvgColor: string;
    DisplayOrder: number;
    Format: string;
    Image: string;
    ImgSize: ImgSize;
    LoadFromFile: boolean;
    Location: string;
    LocationType: number;
}

export interface ImgSize {
    Height: number;
    UseMinHorVerSize: boolean;
    Width: number;
}
