// Generated by https://quicktype.io

export interface TransactionHistoryResponse {
    SalesEntriesGetByCardIdResult: Orders[];
}

export interface Orders {
    Id: string;
    AnonymousOrder: boolean;
    CardId: string;
    ClickAndCollectOrder: boolean;
    DiscountLines: any[];
    DocumentRegTime: string;
    ExternalId: string;
    IdType: number;
    LineItemCount: number;
    Lines: any[];
    PaymentStatus: number;
    Payments: any[];
    PointsRewarded: number;
    PointsUsedInOrder: number;
    Posted: boolean;
    ShipToAddress: null;
    ShipToEmail: null;
    ShipToName: string;
    ShipToPhoneNumber: null;
    ShippingAgentCode: null;
    ShippingAgentServiceCode: null;
    ShippingStatus: number;
    Status: number;
    StoreId: string;
    StoreName: string;
    TerminalId: null;
    TotalAmount: number;
    TotalDiscount: number;
    TotalNetAmount: number;
}
