import { CategoryIDs } from "core/enums";
import { Product } from "core/interfaces";

export const BestSellerItems: Product[] = [
    {
        Id: '81195',
        AllowedToSell: true,
        BlockDiscount: false,
        BlockManualPriceChange: false,
        Blocked: false,
        Description: 'Gtt Blue Ii Plus Set ',
        Details: 'ماكينه الاستخدام الواحد',
        Discount: 0,
        GrossWeight: 0.0,
        Images: [
            {
                Id: '',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location: 'http://delmar-test.linkedgates.com/images/items/81195.JPEG',
                LocationType: 1,
            },
        ],
        IsDeleted: false,
        ItemAttributes: [],
        ItemCategoryCode: CategoryIDs.PerCare,
        ItemFamilyCode: 'M.SUPPLIES',
        ItemPrice: 13.0,
        NewPrice: null,
        Price: '',
        Prices: [
            {
                Amount: '13.00',
                Amt: 13.0,
                ItemId: '81195',
                StoreId: 'WEB',
                UomId: 'EACH',
                VariantId: '',
            },
        ],
        ProductGroupId: 'MEN CARE',
        SalesUomId: 'EACH',
        ScaleItem: false,
        SeasonCode: '',
        SelectedUnitOfMeasure: null,
        SelectedVariant: null,
        UnitOfMeasures: [
            {
                Id: 'EACH',
                Decimals: 0,
                Description: '',
                ItemId: '81195',
                Price: 0,
                QtyPerUom: 1.0,
                ShortDescription: 'EACH',
            },
        ],
        UnitVolume: 0.0,
        UnitsPerParcel: 0.0,
        VariantsExt: [],
        VariantsRegistration: [],
    },
    {
        Id: '134439',
        AllowedToSell: true,
        BlockDiscount: false,
        BlockManualPriceChange: false,
        Blocked: false,
        Description: 'Tresor Expert Facial Cleanser 150 Ml',
        Details: 'غسول مرطب للبشره مع مقشر لطيف لتنظيف عميق',
        Discount: 0,
        GrossWeight: 0.0,
        Images: [
            {
                Id: '',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location: 'http://delmar-test.linkedgates.com/images/items/134439.JPEG',
                LocationType: 1,
            },
        ],
        IsDeleted: false,
        ItemAttributes: [],
        ItemCategoryCode: CategoryIDs.PerCare,
        ItemFamilyCode: 'PER.CARE',
        ItemPrice: 200.0,
        NewPrice: 150,
        Price: '',
        Prices: [
            {
                Amount: '200.00',
                Amt: 200.0,
                ItemId: '134439',
                StoreId: 'WEB',
                UomId: 'EACH',
                VariantId: '',
            },
        ],
        ProductGroupId: 'SKIN CARE',
        SalesUomId: 'EACH',
        ScaleItem: false,
        SeasonCode: '',
        SelectedUnitOfMeasure: null,
        SelectedVariant: null,
        UnitOfMeasures: [
            {
                Id: 'EACH',
                Decimals: 0,
                Description: '',
                ItemId: '134439',
                Price: 0,
                QtyPerUom: 1.0,
                ShortDescription: 'EACH',
            },
        ],
        UnitVolume: 0.0,
        UnitsPerParcel: 0.0,
        VariantsExt: [],
        VariantsRegistration: [],
    },
    {
        Id: '128898',
        AllowedToSell: true,
        BlockDiscount: false,
        BlockManualPriceChange: false,
        Blocked: false,
        Description: 'Gtt Blue 3 Simple  Set',
        Details: 'مكن حلاقة بلو3',
        Discount: 0,
        GrossWeight: 0.0,
        Images: [
            {
                Id: '',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location: 'http://delmar-test.linkedgates.com/images/items/128898.JPEG',
                LocationType: 1,
            },
        ],
        IsDeleted: false,
        ItemAttributes: [],
        ItemCategoryCode: CategoryIDs.PerCare,
        ItemFamilyCode: 'M.SUPPLIES',
        ItemPrice: 18.0,
        NewPrice: null,
        Price: '',
        Prices: [
            {
                Amount: '18.00',
                Amt: 18.0,
                ItemId: '128898',
                StoreId: 'WEB',
                UomId: 'EACH',
                VariantId: '',
            },
        ],
        ProductGroupId: 'MEN CARE',
        SalesUomId: 'EACH',
        ScaleItem: false,
        SeasonCode: '',
        SelectedUnitOfMeasure: null,
        SelectedVariant: null,
        UnitOfMeasures: [
            {
                Id: 'EACH',
                Decimals: 0,
                Description: '',
                ItemId: '128898',
                Price: 0,
                QtyPerUom: 1.0,
                ShortDescription: 'EACH',
            },
        ],
        UnitVolume: 0.0,
        UnitsPerParcel: 0.0,
        VariantsExt: [],
        VariantsRegistration: [],
    },
    {
        Id: '130144',
        AllowedToSell: true,
        BlockDiscount: false,
        BlockManualPriceChange: false,
        Blocked: false,
        Description: 'Macro Panthenol Cream 50 Ml',
        Details: 'مرطب وملطف للجلد',
        Discount: 0,
        GrossWeight: 0.0,
        Images: [
            {
                Id: '',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location: 'http://delmar-test.linkedgates.com/images/items/130144.JPEG',
                LocationType: 1,
            },
        ],
        IsDeleted: false,
        ItemAttributes: [],
        ItemCategoryCode: CategoryIDs.PerCare,
        ItemFamilyCode: 'PER.CARE',
        ItemPrice: 45.0,
        NewPrice: null,
        Price: '',
        Prices: [
            {
                Amount: '45.00',
                Amt: 45.0,
                ItemId: '130144',
                StoreId: 'WEB',
                UomId: 'EACH',
                VariantId: '',
            },
        ],
        ProductGroupId: 'SKIN CARE',
        SalesUomId: 'EACH',
        ScaleItem: false,
        SeasonCode: '',
        SelectedUnitOfMeasure: null,
        SelectedVariant: null,
        UnitOfMeasures: [
            {
                Id: 'EACH',
                Decimals: 0,
                Description: '',
                ItemId: '130144',
                Price: 0,
                QtyPerUom: 1.0,
                ShortDescription: 'EACH',
            },
        ],
        UnitVolume: 0.0,
        UnitsPerParcel: 0.0,
        VariantsExt: [],
        VariantsRegistration: [],
    },
    {
        Id: '103898',
        AllowedToSell: true,
        BlockDiscount: false,
        BlockManualPriceChange: false,
        Blocked: false,
        Description: 'Oral-B 1.2.3 (40) (M) Touth Brush',
        Details: 'فرشاة اسنان اورال بى',
        Discount: 0,
        GrossWeight: 0.0,
        Images: [
            {
                Id: '',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location: 'http://delmar-test.linkedgates.com/images/items/103898.JPEG',
                LocationType: 1,
            },
        ],
        IsDeleted: false,
        ItemAttributes: [],
        ItemCategoryCode: CategoryIDs.PerCare,
        ItemFamilyCode: 'M.SUPPLIES',
        ItemPrice: 26.19,
        NewPrice: null,
        Price: '',
        Prices: [
            {
                Amount: '26.19',
                Amt: 26.19,
                ItemId: '103898',
                StoreId: 'WEB',
                UomId: 'EACH',
                VariantId: '',
            },
        ],
        ProductGroupId: 'MOUTH CARE',
        SalesUomId: 'EACH',
        ScaleItem: false,
        SeasonCode: '',
        SelectedUnitOfMeasure: null,
        SelectedVariant: null,
        UnitOfMeasures: [
            {
                Id: 'EACH',
                Decimals: 0,
                Description: '',
                ItemId: '103898',
                Price: 0,
                QtyPerUom: 1.0,
                ShortDescription: 'EACH',
            },
        ],
        UnitVolume: 0.0,
        UnitsPerParcel: 0.0,
        VariantsExt: [],
        VariantsRegistration: [],
    },
    {
        Id: '28313',
        AllowedToSell: true,
        BlockDiscount: false,
        BlockManualPriceChange: false,
        Blocked: false,
        Description: 'Nizapex Shampoo 80 Ml',
        Details:
            'شامبو لعلاج قشره الشعر  / الاستعمال :يوضع على فروة الراس لمدة 5 دقايق ثم يشطف بالماء يكرر الاستعمال يوم بعد يوم لمدة شهر ونصف',
        Discount: 0,
        GrossWeight: 0.0,
        Images: [
            {
                Id: '',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location: 'http://delmar-test.linkedgates.com/images/items/28313.JPEG',
                LocationType: 1,
            },
        ],
        IsDeleted: false,
        ItemAttributes: [],
        ItemCategoryCode: CategoryIDs.PerCare,
        ItemFamilyCode: 'PER.CARE',
        ItemPrice: 34.0,
        NewPrice: null,
        Price: '',
        Prices: [
            {
                Amount: '34.00',
                Amt: 34.0,
                ItemId: '28313',
                StoreId: 'WEB',
                UomId: 'EACH',
                VariantId: '',
            },
        ],
        ProductGroupId: 'HAIR CARE',
        SalesUomId: 'EACH',
        ScaleItem: false,
        SeasonCode: '',
        SelectedUnitOfMeasure: null,
        SelectedVariant: null,
        UnitOfMeasures: [
            {
                Id: 'EACH',
                Decimals: 0,
                Description: '',
                ItemId: '28313',
                Price: 0,
                QtyPerUom: 1.0,
                ShortDescription: 'EACH',
            },
        ],
        UnitVolume: 0.0,
        UnitsPerParcel: 0.0,
        VariantsExt: [],
        VariantsRegistration: [],
    },
];
