import { AdvertisementsAppTypes } from 'core/enums';
import { Advertisement } from 'core/interfaces';

export const Advertisements: Advertisement[] = [
    {
        AdType: 0,
        AdValue: '',
        AppType: AdvertisementsAppTypes.magazine,
        AppValue: 'https://online.fliphtml5.com/gjkwf/siey/',
        ArabicDescription: '',
        Description: 'Valentine Magazine 2022',
        ExpirationDate: '/Date(4102437600000+0200)/',
        Id: 'SIDE BAR 1',
        ImageView: {
            Id: 'SIDE BAR 1',
            AvgColor: '',
            DisplayOrder: 0,
            Format: '',
            Image: '',
            ImgSize: {
                Height: 0,
                UseMinHorVerSize: false,
                Width: 0,
            },
            LoadFromFile: false,
            Location:
                'https://delmar-test.linkedgates.com/images/ads/SIDE BAR 1.JPEG',
            LocationType: 1,
        },
        MenuIds: [],
        RV: 0,
    },
    {
        AdType: 0,
        AdValue: '',
        AppType: AdvertisementsAppTypes.item,
        AppValue: '17938',
        ArabicDescription: '',
        Description: 'Vaxigrip',
        ExpirationDate: '/Date(4102437600000+0200)/',
        Id: 'SIDE BAR 2',
        ImageView: {
            Id: 'SIDE BAR 2',
            AvgColor: '',
            DisplayOrder: 0,
            Format: '',
            Image: '',
            ImgSize: {
                Height: 0,
                UseMinHorVerSize: false,
                Width: 0,
            },
            LoadFromFile: false,
            Location:
                'https://delmar-test.linkedgates.com/images/ads/SIDE BAR 2.JPEG',
            LocationType: 1,
        },
        MenuIds: [],
        RV: 0,
    },
    {
        AdType: 0,
        AdValue: '',
        AppType: AdvertisementsAppTypes.search,
        AppValue: 'MEDICINE,VITAMINS',
        ArabicDescription: '',
        Description: 'Vitamins',
        ExpirationDate: '/Date(4102437600000+0200)/',
        Id: 'SIDE BAR 3',
        ImageView: {
            Id: 'SIDE BAR 3',
            AvgColor: '',
            DisplayOrder: 0,
            Format: '',
            Image: '',
            ImgSize: {
                Height: 0,
                UseMinHorVerSize: false,
                Width: 0,
            },
            LoadFromFile: false,
            Location:
                'https://delmar-test.linkedgates.com/images/ads/SIDE BAR 3.JPEG',
            LocationType: 1,
        },
        MenuIds: [],
        RV: 0,
    },
    {
        AdType: 0,
        AdValue: '',
        AppType: AdvertisementsAppTypes.offer,
        AppValue: 'PU-000001216',
        ArabicDescription: '',
        Description: 'Tresor Roll On',
        ExpirationDate: '/Date(4102437600000+0200)/',
        Id: 'SIDE BAR 4',
        ImageView: {
            Id: 'SIDE BAR 4',
            AvgColor: '',
            DisplayOrder: 0,
            Format: '',
            Image: '',
            ImgSize: {
                Height: 0,
                UseMinHorVerSize: false,
                Width: 0,
            },
            LoadFromFile: false,
            Location:
                'https://delmar-test.linkedgates.com/images/ads/SIDE BAR 4.JPEG',
            LocationType: 1,
        },
        MenuIds: [],
        RV: 0,
    },
    {
        AdType: 0,
        AdValue: '',
        AppType: AdvertisementsAppTypes.search,
        AppValue: 'PER.CARE,BODY CARE,V-0261',
        ArabicDescription: '',
        Description: 'Tresor Shower-Body Splash',
        ExpirationDate: '/Date(4102437600000+0200)/',
        Id: 'SIDE BAR 5',
        ImageView: {
            Id: 'SIDE BAR 5',
            AvgColor: '',
            DisplayOrder: 0,
            Format: '',
            Image: '',
            ImgSize: {
                Height: 0,
                UseMinHorVerSize: false,
                Width: 0,
            },
            LoadFromFile: false,
            Location:
                'https://delmar-test.linkedgates.com/images/ads/SIDE BAR 5.JPEG',
            LocationType: 1,
        },
        MenuIds: [],
        RV: 0,
    },
];
