export const Offers = [
    {
        Id: 'PU-000001346',
        ArabicText:
            'عرض ميد كير منتجات العناية بالبشرة والشعر خصم 30% على القطعة من 1-5 حتى 31-5',
        Code: 4,
        Description: 'med care 30%  May',
        Details:
            'Medcare offers 30% discount on skincare and hair care products per item from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003957-1',
                AvgColor: '',
                DisplayOrder: 1,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001346.JPEG',
                LocationType: 1,
            },
            {
                Id: 'DIS0003957-2',
                AvgColor: '',
                DisplayOrder: 2,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001346.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003957',
        OfferLines: [
            {
                Id: '127266',
                Description: 'Virju Gold Z For Hair Loss Hair Lotion 200 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '127265',
                Description: 'Neja Gold Z For Hair Loss Shampoo 200 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139940',
                Description: 'Goldz Jolibeau Eye Cream 15 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 25000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139937',
                Description: 'Goldz Signora Hair Loss Spray 150 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 30000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '127267',
                Description: 'Ojone Gold Z Hair Serum 50 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 35000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '902143',
                Description: 'Goldz Prodence Danaruff Shampoo 200 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 40000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139939',
                Description: 'Goldz Moonpearly Hair Mask Cream 200 Gm',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 50000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139938',
                Description: 'Dermaz Turffle Anti-Aging Cream 30 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 60000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '128012',
                Description: 'Dermaz Su Jallant Sun Screen Lotion 100 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 70000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '131158',
                Description: 'Dermaz Su Jallant Sun Screen 50 + Sun Cream 100 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 80000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '126117',
                Description: 'Dermaz Purg Cleansing Gel 200 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 90000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '132006',
                Description: 'Dermaz Nosca Emollient Repairing Cream 100 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 100000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139948',
                Description: 'Dermaz Monaco Plush Medium Concealer 10 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 110000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139949',
                Description: 'Dermaz Monaco Plush Light Concealer 10 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 120000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139947',
                Description: 'Dermaz Monaco Medium Sand Foundation 30 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 130000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139946',
                Description: 'Dermaz Monaco Light Ivory Foundation 30 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 140000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139941',
                Description: 'Dermaz Mb All In 1 Micellar Water  250 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 150000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '132005',
                Description: 'Dermaz Gloomy Arbuti Spf 30 Whitening Cream 100 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 160000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139945',
                Description: 'Dermaz Clockface Face & Neck Serum 30Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 170000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '125794',
                Description: 'Argan Z Pure Argan Oil 50 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 180000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '132004',
                Description: 'Argan Z Pure Argan Oil 100 Ml',
                DiscountId: 'DIS0003957',
                DiscountType: 4,
                Exclude: false,
                LineNo: 190000,
                LineType: 0,
                OfferId: 'PU-000001346',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001351',
        ArabicText:
            'عرض تويست & جو منتجات العناية بالشعر خصم 50% على القطعة الثانية من 1-5 حتى 31-5',
        Code: 3,
        Description: 'twist &go1+50% 1-31 May',
        Details:
            'Twist & Go offers 50% discount on the second item of hair care products from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003926',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001351.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003926',
        OfferLines: [
            {
                Id: '1256',
                Description: '',
                DiscountId: 'DIS0003926',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 4,
                OfferId: 'PU-000001351',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001355',
        ArabicText:
            'عرض سومافي منتجات العناية بالشعر الكيرلى  خصم 50% على القطعة الثانية من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Somavie 1+50% 1-31 May',
        Details:
            'Somavie offers 50% discount on the second item of curly hair care products from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003939',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001355.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003939',
        OfferLines: [
            {
                Id: '1260',
                Description: '',
                DiscountId: 'DIS0003939',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 4,
                OfferId: 'PU-000001355',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001357',
        ArabicText:
            'عرض لوريال إلفيف دريم 8 سكند وندر ووتر 200 مل خصم 30% على القطعة من 1-5 حتى 31-5',
        Code: 4,
        Description: 'Loreal Elvive Dream 30% May',
        Details:
            "L'Oreal Elvive Dream 8 Second Wonder Water 200ml is discounted by 30% per piece from 1-5 until 31-5.",
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003977',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001357.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003977',
        OfferLines: [
            {
                Id: '138744',
                Description: 'Loreal Elvive Dream  8 Second Wonder Water 200 Ml',
                DiscountId: 'DIS0003977',
                DiscountType: 4,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001357',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001359',
        ArabicText: 'عرض كولاجرا كونسيلار خصم 40% على القطعة من 1-5 حتى 31-5',
        Code: 4,
        Description: 'Kolagra Medi +light 40% May ',
        Details:
            'Kolagra Concealer in Medium and Light shades are discounted by 40% per piece from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003959',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001359.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003959',
        OfferLines: [
            {
                Id: '139933',
                Description: 'Kolagra Perfecting Concealer Medium10 Ml',
                DiscountId: 'DIS0003959',
                DiscountType: 4,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001359',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139989',
                Description: 'Kolagra Perfecting Concealer Light 10 Ml',
                DiscountId: 'DIS0003959',
                DiscountType: 4,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001359',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001370',
        ArabicText:
            'عرض ديفول كيدز  منتجات العناية باالشعر الاطفال والشعر الكيرلى خصم 10% على القطعة من 1-5 حتى 31-5',
        Code: 4,
        Description: 'Divol Kids 10% May',
        Details:
            'Divol Kids hair care products for children, including curly hair, are discounted by 10% per piece from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003962',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001370.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003962',
        OfferLines: [
            {
                Id: '140154',
                Description: 'Divol Kids For Oily Hair Shampoo 500 Ml',
                DiscountId: 'DIS0003962',
                DiscountType: 4,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001370',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '140155',
                Description: 'Divol Kids Strawberry Shower Gel 500 Ml',
                DiscountId: 'DIS0003962',
                DiscountType: 4,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001370',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '140156',
                Description: 'Divol Kids For Dry Hair Shampoo 500 Ml',
                DiscountId: 'DIS0003962',
                DiscountType: 4,
                Exclude: false,
                LineNo: 30000,
                LineType: 0,
                OfferId: 'PU-000001370',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '140157',
                Description: 'Divol Kids Leave In Cream 250 Gm',
                DiscountId: 'DIS0003962',
                DiscountType: 4,
                Exclude: false,
                LineNo: 40000,
                LineType: 0,
                OfferId: 'PU-000001370',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '140159',
                Description: 'Divol Kids Blueberry Shower Gel 500 Ml',
                DiscountId: 'DIS0003962',
                DiscountType: 4,
                Exclude: false,
                LineNo: 50000,
                LineType: 0,
                OfferId: 'PU-000001370',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '140160',
                Description: 'Divol Kids Hair Serum 100 Ml',
                DiscountId: 'DIS0003962',
                DiscountType: 4,
                Exclude: false,
                LineNo: 60000,
                LineType: 0,
                OfferId: 'PU-000001370',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '140161',
                Description: 'Divol Kids For Oily Hair Shampoo 300 Ml',
                DiscountId: 'DIS0003962',
                DiscountType: 4,
                Exclude: false,
                LineNo: 70000,
                LineType: 0,
                OfferId: 'PU-000001370',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '140162',
                Description: 'Divol Kids For Dry Hair Shampoo 300 Ml',
                DiscountId: 'DIS0003962',
                DiscountType: 4,
                Exclude: false,
                LineNo: 80000,
                LineType: 0,
                OfferId: 'PU-000001370',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '140163',
                Description: 'Divol Kids Hair Styling Cream 250 Gm',
                DiscountId: 'DIS0003962',
                DiscountType: 4,
                Exclude: false,
                LineNo: 90000,
                LineType: 0,
                OfferId: 'PU-000001370',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '140224',
                Description: 'Divol Kids For Dry Hair Conditioner 500 Ml',
                DiscountId: 'DIS0003962',
                DiscountType: 4,
                Exclude: false,
                LineNo: 100000,
                LineType: 0,
                OfferId: 'PU-000001370',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001371',
        ArabicText:
            'اشترى عبوة بيبي ستيبس حليب الماعز مرحلة ثالثة (3) واحصلى على  عبوة  مجانية بيبي ستيبس 300 مجم من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Baby steps 2+1 1-31 May',
        Details:
            'Buy a pack of Baby Steps Goat Milk Stage 3 formula and get a free 300ml pack of Baby Steps formula from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003929',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001371.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003929',
        OfferLines: [
            {
                Id: '135142',
                Description: 'Baby Steps 300 Mg 2 Sachets',
                DiscountId: 'DIS0003929',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001371',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '137942',
                Description: 'Baby Steps Stage (3) 12-36 M Goat Milk 300 GM',
                DiscountId: 'DIS0003929',
                DiscountType: 3,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001371',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001372',
        ArabicText:
            'عرض بي بي اس 300 مجم اشترى 3 علبة  واحصلى على الرابعة مجانا من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Baby steps 300mg 3+1 May',
        Details:
            'BBS 300mg lgG buy 3 packs and get the 4th for free from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003930',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001372.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003930',
        OfferLines: [
            {
                Id: '135151',
                Description: 'BBS 300mg lgG',
                DiscountId: 'DIS0003930',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001372',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001373',
        ArabicText:
            'عرض بيبي ستيبس 300 مجم اشترى 3 علبة  واحصلى على الرابعة مجانا من  1-5 حتى 31-5',
        Code: 3,
        Description: 'Baby steps 3 3+1 May',
        Details:
            'Baby Steps 300mg buy 3 packs and get the 4th for free from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003931',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001373.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003931',
        OfferLines: [
            {
                Id: '135142',
                Description: 'Baby Steps 300 Mg 2 Sachets',
                DiscountId: 'DIS0003931',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001373',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001374',
        ArabicText:
            'اشترى عبوتين بيبي ستيبس حليب الماعز مرحلة ثالثة (3) واحصلى على العبوة الثالثة مجانيه من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Baby Steps Stage (3) 2+1 May',
        Details:
            'Buy two packs of Baby Steps Goat Milk Stage 3 formula and get the third pack for free from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003932',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001374.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003932',
        OfferLines: [
            {
                Id: '137942',
                Description: 'Baby Steps Stage (3) 12-36 M Goat Milk 300 GM',
                DiscountId: 'DIS0003932',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001374',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001375',
        ArabicText:
            'اشترى عبوتين بيبي ستيبس حليب الماعز مرحلة تانية (2) واحصلى على العبوة الثالثة مجانيه من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Baby Steps 2 1-31 May',
        Details:
            'Buy two packs of Baby Steps Goat Milk Stage 2 formula and get the third pack for free from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003933',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001375.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003933',
        OfferLines: [
            {
                Id: '137941',
                Description: 'Baby Steps Stage (2) 6-12 M Goat Milk 300 GM',
                DiscountId: 'DIS0003933',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001375',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001376',
        ArabicText: 'عرض فاين كير للكبار خصم 10% على القطعة من 1-5 حتى 31-5',
        Code: 4,
        Description: 'Fine Care 10% 1-31 May ',
        Details: 'Fine Care offers a 10% discount on items 1-5 until May 31st.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003975',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001376.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003975',
        OfferLines: [
            {
                Id: '119576',
                Description: 'Fine Care Large Short 100 -140 Cm 14 Pads',
                DiscountId: 'DIS0003975',
                DiscountType: 4,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001376',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '119575',
                Description: 'Fine Care Large 110 -156 Cm 36Pads',
                DiscountId: 'DIS0003975',
                DiscountType: 4,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001376',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '127002',
                Description: 'Fine Care Large 110 -156 Cm 18 Pads',
                DiscountId: 'DIS0003975',
                DiscountType: 4,
                Exclude: false,
                LineNo: 30000,
                LineType: 0,
                OfferId: 'PU-000001376',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '127000',
                Description: 'Fine Care Adult Small 18 Pad 51-75Cm برتقالى',
                DiscountId: 'DIS0003975',
                DiscountType: 4,
                Exclude: false,
                LineNo: 40000,
                LineType: 0,
                OfferId: 'PU-000001376',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '133960',
                Description: 'Fine Care Adult Small 12 Pad 51-57Cm برتقالى',
                DiscountId: 'DIS0003975',
                DiscountType: 4,
                Exclude: false,
                LineNo: 50000,
                LineType: 0,
                OfferId: 'PU-000001376',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '120696',
                Description: 'Fine Care Adult Medium 2 Pad75-110',
                DiscountId: 'DIS0003975',
                DiscountType: 4,
                Exclude: false,
                LineNo: 60000,
                LineType: 0,
                OfferId: 'PU-000001376',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '111997',
                Description: 'Fine Care Adult Medium 11 Pad75-110 ازرق',
                DiscountId: 'DIS0003975',
                DiscountType: 4,
                Exclude: false,
                LineNo: 70000,
                LineType: 0,
                OfferId: 'PU-000001376',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '133959',
                Description: 'Fine Care Adult Medium  75-110Cm 44 Pad',
                DiscountId: 'DIS0003975',
                DiscountType: 4,
                Exclude: false,
                LineNo: 80000,
                LineType: 0,
                OfferId: 'PU-000001376',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '127001',
                Description: 'Fine Care Adult Medium  75-110Cm  22 Pad',
                DiscountId: 'DIS0003975',
                DiscountType: 4,
                Exclude: false,
                LineNo: 90000,
                LineType: 0,
                OfferId: 'PU-000001376',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '113073',
                Description: 'Fine Care Adult Large 9 Pad110-156 Cm اخضر',
                DiscountId: 'DIS0003975',
                DiscountType: 4,
                Exclude: false,
                LineNo: 100000,
                LineType: 0,
                OfferId: 'PU-000001376',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001377',
        ArabicText: 'عرض فاين بيبي  الجامبو خصم 10% على القطعة من 1-5 حتى 31-5',
        Code: 4,
        Description: 'Fine Baby 10% May',
        Details:
            'Fine Baby offers a 10% discount on Jumbo items 1-5 until May 31st.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003976',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001377.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003976',
        OfferLines: [
            {
                Id: '139881',
                Description: 'Fine Baby (5) Maxi 10-22 Kg 58 Diapers',
                DiscountId: 'DIS0003976',
                DiscountType: 4,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001377',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139878',
                Description: 'Fine Baby (4) Large 7-14 Kg 58 Diapers',
                DiscountId: 'DIS0003976',
                DiscountType: 4,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001377',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139880',
                Description: 'Fine Baby (3) Medium 4-9 Kg 58 Diapers',
                DiscountId: 'DIS0003976',
                DiscountType: 4,
                Exclude: false,
                LineNo: 30000,
                LineType: 0,
                OfferId: 'PU-000001377',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139876',
                Description: 'Fine Baby (2) Small  3-6 Kg  58 Diapers',
                DiscountId: 'DIS0003976',
                DiscountType: 4,
                Exclude: false,
                LineNo: 40000,
                LineType: 0,
                OfferId: 'PU-000001377',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139879',
                Description: 'Fine Baby (1) Newborn 2-5 Kg 60 Diapers',
                DiscountId: 'DIS0003976',
                DiscountType: 4,
                Exclude: false,
                LineNo: 50000,
                LineType: 0,
                OfferId: 'PU-000001377',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001380',
        ArabicText:
            'اشترى علبة  فيتامين بروفى كيدز 120 قطعة  واحصلى على علبة  فيتامين سيرفيللو 60  قطعة  مجانا من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Profi120 + cervello 60 May',
        Details:
            'Buy a box of Profi Kids Vitamins 120 pieces and get a box of Cervello Vitamins 60 pieces for free from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003934',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001380.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003934',
        OfferLines: [
            {
                Id: '138553',
                Description: 'Cervello Omega 3+Vitamin B Complex 60 Kids Gummies',
                DiscountId: 'DIS0003934',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001380',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138555',
                Description: 'Profi Multi Vitamins 120 Kids Gummies',
                DiscountId: 'DIS0003934',
                DiscountType: 3,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001380',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001381',
        ArabicText:
            'اشترى علبه فيتامين سيرفيللو 120 قطعة واحصلى على علبة فيتامين بروفى كيدز 60 قطعة مجانا من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Cervello120+ prof 60 May',
        Details:
            'Buy a box of Cervello Vitamins 120 pieces and get a box of Profi Kids Vitamins 60 pieces for free from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003935',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001381.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003935',
        OfferLines: [
            {
                Id: '138554',
                Description: 'Cervello Omega 3+Vitamin B Complex120 Kids Gummies',
                DiscountId: 'DIS0003935',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001381',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138556',
                Description: 'Profi Multi Vitamins 60 Kids Gummies',
                DiscountId: 'DIS0003935',
                DiscountType: 3,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001381',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001382',
        ArabicText:
            'اشترى علبة مينا أوميجا 3 120 جوميز أطفال واحصلي على  الثانية مجانا من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Minna Omega 3 120 May',
        Details:
            'Buy a box of Minna Omega 3 120 gummies for children and get the second one for free from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003936',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001382.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003936',
        OfferLines: [
            {
                Id: '137787',
                Description: 'Minna Omega 3 120 Gummies KIDS',
                DiscountId: 'DIS0003936',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001382',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001383',
        ArabicText:
            'اشترى علبة مينا أوميجا 3 60 توميز أطفال واحصلى على الثانية  مجانا من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Minna Omega 3 60  May',
        Details:
            'Buy a box of Minna Omega 3 60 gummies for children and get the second one for free from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003937',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001383.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003937',
        OfferLines: [
            {
                Id: '137782',
                Description: 'Minna Omega 3 60 Gummies KIDS',
                DiscountId: 'DIS0003937',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001383',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001384',
        ArabicText:
            'اشترى علبة اي او كير واى بروتين للاطفال واحصلى على الثانية مجانا  من 1-5 حتى 31-5',
        Code: 3,
        Description: 'IO Care-10 sachet May',
        Details:
            'Buy a box of IO Care Whey Protein for Kids 10 Sachet and get the second one for free from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003938',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001384.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003938',
        OfferLines: [
            {
                Id: '139156',
                Description: 'IO Care Whey Protein For Kids 10 Sachet',
                DiscountId: 'DIS0003938',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001384',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001385',
        ArabicText: 'عرض فيتامينات ناترول خصم 15% على القطعة من 1-5 حتى 31-5',
        Code: 4,
        Description: 'Vitamin Natrol 15% May',
        Details:
            'Vitamin Natrol offers a 15% discount on items 1-5 until May 31st.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003966',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001385.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003966',
        OfferLines: [
            {
                Id: '139942',
                Description: 'Life Extension Optimized folate 1700 mcg 100 Tab',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139943',
                Description: 'Life Extension Potassium With Magnesium 60 Cap',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138092',
                Description: 'Natrol Acai Berry 60 Caps',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 30000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138323',
                Description: 'Natrol Acidophilus Probiotic 150 Cap',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 40000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138093',
                Description: 'Natrol B-Complex Energy Support 90 Tab ',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 50000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138097',
                Description: 'Natrol Biotin 10.000 Mcg 100 Tab',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 60000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139628',
                Description: 'Natrol Biotin 5000 Mcg Strawberry 90 Tab',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 70000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138435',
                Description: 'Natrol Collagen Skin Renewal 120 Cap',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 80000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139621',
                Description: 'Natrol Extreme Omega 2400 Mg Lemon 60 Softgels',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 90000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138098',
                Description: 'Natrol Ginkgo Biloba 120mg 60Caps',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 100000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138324',
                Description: 'Natrol Glucosamine & MSM 90 Cap',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 110000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138322',
                Description: 'Natrol L-Arginine 3,000 Mg 90 Tab ',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 120000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138096',
                Description: 'Natrol Magnesium 250mg 60Tab',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 130000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138091',
                Description: 'Natrol Melatonin 3 Gm 100 Tab',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 140000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138090',
                Description: 'Natrol Melatonin 5 Gm 100 Tab',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 150000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139666',
                Description: 'Natrol Omega-3 Fish Oil 1000mg 150 Softgel',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 160000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138095',
                Description: 'Natrol Omega-3 Fish Oil 1000mg 90 Softgel',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 170000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138242',
                Description: 'Natrol Omega-3 Fish Oil 1200mg 60 Softgel',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 180000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138514',
                Description: 'Natrol Omega-3-6-9 Complex 1200mg 90 Caps',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 190000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138434',
                Description: 'Natrol Skin & Hair & Nails 60Cap',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 200000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139625',
                Description: 'Natrol Turmeric Joint Mobility 60 Caps ',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 210000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138094',
                Description: 'Natrol Vitamin D3 10.000 IU 60Tab',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 220000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138099',
                Description: 'Natrol Vitamin D3 5000 IU 90 Tab',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 230000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '139667',
                Description: 'Sugarbear Hair Vitamins 74 Gummies',
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 240000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138100',
                Description: "Sugarbear Women's Multi 60 Gum",
                DiscountId: 'DIS0003966',
                DiscountType: 4,
                Exclude: false,
                LineNo: 250000,
                LineType: 0,
                OfferId: 'PU-000001385',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001386',
        ArabicText:
            'اشترى علبة ريجيماكس 120مجم 30 كبسول واحصلى على هيرباتريند اعشاب تخسيس مجانا من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Regimax+Herba May',
        Details:
            'Buy a box of Regimax 120 Mg 30 Cap and get a free box of Herba Trend weight loss herbs from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003940',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001386.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003940',
        OfferLines: [
            {
                Id: '132600',
                Description: 'Regimax 120 Mg 30 Cap',
                DiscountId: 'DIS0003940',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001386',
                UnitOfMeasure: 'EACH',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '130850',
                Description: 'Herba Trend Slimming  Fatburner Tea 10 Bags',
                DiscountId: 'DIS0003940',
                DiscountType: 3,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001386',
                UnitOfMeasure: 'EACH',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001387',
        ArabicText:
            'اشترى علبة مادوفيت إيف الوفيرا للسيدات 30 قرص واحصلى على مادوكس فيتاسيد سى 20 قرص فوار \n مجانا من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Maddox+Maddovit 1-31 May',
        Details:
            'Buy a box of Maddovit Eve+Aloevera 30 Tab and get a free box of Maddox Multi Vitamin Orange from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003946',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001387.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003946',
        OfferLines: [
            {
                Id: '136676',
                Description: 'Maddox Multi Vitamin orange  20 EFF Tablets ',
                DiscountId: 'DIS0003946',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001387',
                UnitOfMeasure: 'EACH',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '138364',
                Description: 'Maddovit Eve+Aloevera 30 Tab',
                DiscountId: 'DIS0003946',
                DiscountType: 3,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001387',
                UnitOfMeasure: 'EACH',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001388',
        ArabicText:
            'اشترى علبة مادوفيت 30 قرص واحصلى على مادوكس فوار برتقال مجانا من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Maddox+maddovit30 May',
        Details:
            'Buy a box of Maddovit 30 Tab and get a free box of Maddox Multi Vitamin Orange from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003947',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001388.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003947',
        OfferLines: [
            {
                Id: '136676',
                Description: 'Maddox Multi Vitamin orange  20 EFF Tablets ',
                DiscountId: 'DIS0003947',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001388',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '134522',
                Description: 'Maddovit 30 Tab',
                DiscountId: 'DIS0003947',
                DiscountType: 3,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001388',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001389',
        ArabicText:
            'اشترى علبة مادوفيت 100 قرص واحصلى على مادوفيت 30 قرص مجانا من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Maddovit 100+Maddovit 30 May',
        Details:
            'Buy a box of Maddovit 100 Tab and get a free box of Maddovit 30 Tab from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003948',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001389.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003948',
        OfferLines: [
            {
                Id: '134741',
                Description: 'Maddovit 100Tab',
                DiscountId: 'DIS0003948',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001389',
                UnitOfMeasure: 'EACH',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '134522',
                Description: 'Maddovit 30 Tab',
                DiscountId: 'DIS0003948',
                DiscountType: 3,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001389',
                UnitOfMeasure: 'EACH',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001390',
        ArabicText:
            'منتجات ممادوكس فيتامينات أقراص فوارة اشترى علبة واحصلى على الثانية  مجانا من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Maddox1+1 May',
        Details:
            'Buy a box of Maddox Vitamin EFF Tablets and get the second one for free from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003949',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001390.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003949',
        OfferLines: [
            {
                Id: '1263',
                Description: '',
                DiscountId: 'DIS0003949',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 4,
                OfferId: 'PU-000001390',
                UnitOfMeasure: '',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001391',
        ArabicText:
            'اشترى علبة كركملوكس بلس 30 كبسولة واحصلى على علبة مادوكس كالسيوم وفيتامين د3 برتقالي 20 قرص فوار مجانا من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Curcumlox+Maddox May',
        Details:
            'Buy a box of Curcumlox Plus 30 Liquid Cap and get a free box of Maddox Calcium & Vitamin D3 Orange 20 EFF Tablets from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003950',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001391.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003950',
        OfferLines: [
            {
                Id: '140094',
                Description: 'Curcumlox Plus 30 Liquid Cap',
                DiscountId: 'DIS0003950',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001391',
                UnitOfMeasure: 'EACH',
                Variant: '',
                VariantType: 0,
            },
            {
                Id: '136178',
                Description: 'Maddox Calcium & Vitamin D3 Orange 20 EFF Tablets ',
                DiscountId: 'DIS0003950',
                DiscountType: 3,
                Exclude: false,
                LineNo: 20000,
                LineType: 0,
                OfferId: 'PU-000001391',
                UnitOfMeasure: 'EACH',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001393',
        ArabicText:
            'اشترى علبة ايريكتاليس  20 مج 2 قرص واحصلى على 50% خصم على القطعة الثانية من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Erectalis1+50 May',
        Details:
            'Buy a box of Erectalis 20 Mg 2 Tab and get 50% off the second item purchased from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003941',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001393.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003941',
        OfferLines: [
            {
                Id: '117239',
                Description: 'Erectalis 20 Mg 2 Tab',
                DiscountId: 'DIS0003941',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001393',
                UnitOfMeasure: 'EACH',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001394',
        ArabicText:
            'اشترى علبة ديلبي 60 مج 3 قرص واحصلى على  50% خصم على القطعة الثانية من 1-5 حتى 31-5',
        Code: 3,
        Description: 'Delepe 1+50 May',
        Details:
            'Buy a box of Delepe 60 Mg 3 Film and get 50% off the second item purchased from 1-5 until 31-5.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003942',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001394.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003942',
        OfferLines: [
            {
                Id: '105870',
                Description: 'Delepe 60 Mg 3 Film',
                DiscountId: 'DIS0003942',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001394',
                UnitOfMeasure: 'EACH',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001395',
        ArabicText:
            'اشترى علبة ديامونريكتا 20 مج 4 قرص واحصل على خصم 50% على القطعة الثانية من 1-5 حتى 15-5',
        Code: 3,
        Description: 'Diamonrecta 1+50 May',
        Details:
            'Buy a box of Diamonrecta 20 Mg 4 Tab and get a 50% discount on the second item purchased from May 1st-5th until May 15th.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003943',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001395.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003943',
        OfferLines: [
            {
                Id: '128999',
                Description: 'Diamonrecta 20 Mg 4 Tab',
                DiscountId: 'DIS0003943',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001395',
                UnitOfMeasure: 'EACH',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
    {
        Id: 'PU-000001396',
        ArabicText:
            'اشترى علبة تاردانزا 60 مج 3 قرص واحصل على خصم 50% على القطعة الثانية من 1-5 حتى 15-5',
        Code: 3,
        Description: 'Tardanza 60 Mg 1+50 May',
        Details:
            'Buy a box of Tardanza 60 Mg 3 Tab and get a 50% discount on the second item purchased from May 1st-5th until May 15th.',
        ExpirationDate: '/Date(1685487600000+0300)/',
        Images: [
            {
                Id: 'DIS0003944',
                AvgColor: '',
                DisplayOrder: 0,
                Format: '',
                Image: '',
                ImgSize: {
                    Height: 0,
                    UseMinHorVerSize: false,
                    Width: 0,
                },
                LoadFromFile: false,
                Location:
                    'http://delmar-test.linkedgates.com/images/offers/PU-000001396.JPEG',
                LocationType: 1,
            },
        ],
        OfferDetails: [],
        OfferId: 'DIS0003944',
        OfferLines: [
            {
                Id: '128395',
                Description: 'Tardanza 60 Mg 3 Tab',
                DiscountId: 'DIS0003944',
                DiscountType: 3,
                Exclude: false,
                LineNo: 10000,
                LineType: 0,
                OfferId: 'PU-000001396',
                UnitOfMeasure: 'EACH',
                Variant: '',
                VariantType: 0,
            },
        ],
        Selected: false,
        Type: 0,
        ValidationText: '',
    },
];
