import { CategoryIDs } from 'core/enums';
import { Product } from 'core/interfaces';

export const Products: Product[] = [
  {
    Id: '119332',
    AllowedToSell: true,
    BlockDiscount: false,
    BlockManualPriceChange: false,
    Blocked: false,
    Description: 'Actimoxiflox 400 Mg 5 Tab',
    Details: '',
    Discount: 0,
    GrossWeight: 0.0,
    Images: [
      {
        Id: '',
        AvgColor: '',
        DisplayOrder: 0,
        Format: '',
        Image: '',
        ImgSize: {
          Height: 0,
          UseMinHorVerSize: false,
          Width: 0,
        },
        LoadFromFile: false,
        Location:
          'https://delmar-test.linkedgates.com/images/items/119332.JPEG',
        LocationType: 1,
      },
    ],
    IsDeleted: false,
    ItemAttributes: [],
    ItemCategoryCode: CategoryIDs.Medicine,
    ItemFamilyCode: 'MEDICINE',
    ItemPrice: 54.0,
    NewPrice: null,
    Price: '',
    Prices: [
      {
        Amount: '54.00',
        Amt: 54.0,
        ItemId: '119332',
        StoreId: 'WEB',
        UomId: 'EACH',
        VariantId: '',
      },
    ],
    ProductGroupId: 'ANTI-BIOTIC',
    SalesUomId: 'EACH',
    ScaleItem: false,
    SeasonCode: '',
    SelectedUnitOfMeasure: null,
    SelectedVariant: null,
    UnitOfMeasures: [
      {
        Id: 'EACH',
        Decimals: 0,
        Description: '',
        ItemId: '119332',
        Price: 0,
        QtyPerUom: 1.0,
        ShortDescription: 'EACH',
      },
    ],
    UnitVolume: 0.0,
    UnitsPerParcel: 0.0,
    VariantsExt: [],
    VariantsRegistration: [],
  },
  {
    Id: '118251',
    AllowedToSell: true,
    BlockDiscount: false,
    BlockManualPriceChange: false,
    Blocked: false,
    Description: 'Advancrib 400 Mg 5 Tab ',
    Details: '',
    Discount: 0,
    GrossWeight: 0.0,
    Images: [
      {
        Id: '',
        AvgColor: '',
        DisplayOrder: 0,
        Format: '',
        Image: '',
        ImgSize: {
          Height: 0,
          UseMinHorVerSize: false,
          Width: 0,
        },
        LoadFromFile: false,
        Location:
          'https://delmar-test.linkedgates.com/images/items/118251.JPEG',
        LocationType: 1,
      },
    ],
    IsDeleted: false,
    ItemAttributes: [],
    ItemCategoryCode: CategoryIDs.Medicine,
    ItemFamilyCode: 'MEDICINE',
    ItemPrice: 59.0,
    NewPrice: null,
    Price: '',
    Prices: [
      {
        Amount: '59.00',
        Amt: 59.0,
        ItemId: '118251',
        StoreId: 'WEB',
        UomId: 'EACH',
        VariantId: '',
      },
    ],
    ProductGroupId: 'ANTI-BIOTIC',
    SalesUomId: 'EACH',
    ScaleItem: false,
    SeasonCode: '',
    SelectedUnitOfMeasure: null,
    SelectedVariant: null,
    UnitOfMeasures: [
      {
        Id: 'EACH',
        Decimals: 0,
        Description: '',
        ItemId: '118251',
        Price: 0,
        QtyPerUom: 1.0,
        ShortDescription: 'EACH',
      },
    ],
    UnitVolume: 0.0,
    UnitsPerParcel: 0.0,
    VariantsExt: [],
    VariantsRegistration: [],
  },
  {
    Id: '128257',
    AllowedToSell: true,
    BlockDiscount: false,
    BlockManualPriceChange: false,
    Blocked: false,
    Description: 'Advomikacin 500 Gm 1 Vial 2 ML Im Iv',
    Details: '',
    Discount: 0,
    GrossWeight: 0.0,
    Images: [
      {
        Id: '',
        AvgColor: '',
        DisplayOrder: 0,
        Format: '',
        Image: '',
        ImgSize: {
          Height: 0,
          UseMinHorVerSize: false,
          Width: 0,
        },
        LoadFromFile: false,
        Location:
          'https://delmar-test.linkedgates.com/images/items/128257.JPEG',
        LocationType: 1,
      },
    ],
    IsDeleted: false,
    ItemAttributes: [],
    ItemCategoryCode: CategoryIDs.Medicine,
    ItemFamilyCode: 'MEDICINE',
    ItemPrice: 16.5,
    NewPrice: null,
    Price: '',
    Prices: [
      {
        Amount: '16.50',
        Amt: 16.5,
        ItemId: '128257',
        StoreId: 'WEB',
        UomId: 'EACH',
        VariantId: '',
      },
    ],
    ProductGroupId: 'ANTI-BIOTIC',
    SalesUomId: 'EACH',
    ScaleItem: false,
    SeasonCode: '',
    SelectedUnitOfMeasure: null,
    SelectedVariant: null,
    UnitOfMeasures: [
      {
        Id: 'EACH',
        Decimals: 0,
        Description: '',
        ItemId: '128257',
        Price: 0,
        QtyPerUom: 1.0,
        ShortDescription: 'EACH',
      },
    ],
    UnitVolume: 0.0,
    UnitsPerParcel: 0.0,
    VariantsExt: [],
    VariantsRegistration: [],
  },
  {
    Id: '62',
    AllowedToSell: true,
    BlockDiscount: false,
    BlockManualPriceChange: false,
    Blocked: false,
    Description: 'Alexoquine 250 Mg 10 Tab',
    Details: '',
    Discount: 0,
    GrossWeight: 0.0,
    Images: [
      {
        Id: '',
        AvgColor: '',
        DisplayOrder: 0,
        Format: '',
        Image: '',
        ImgSize: {
          Height: 0,
          UseMinHorVerSize: false,
          Width: 0,
        },
        LoadFromFile: false,
        Location: 'https://delmar-test.linkedgates.com/images/items/62.JPEG',
        LocationType: 1,
      },
    ],
    IsDeleted: false,
    ItemAttributes: [],
    ItemCategoryCode: CategoryIDs.Medicine,
    ItemFamilyCode: 'MEDICINE',
    ItemPrice: 10.0,
    NewPrice: null,
    Price: '',
    Prices: [
      {
        Amount: '10.00',
        Amt: 10.0,
        ItemId: '62',
        StoreId: 'WEB',
        UomId: 'EACH',
        VariantId: '',
      },
    ],
    ProductGroupId: 'ANTI-BIOTIC',
    SalesUomId: 'EACH',
    ScaleItem: false,
    SeasonCode: '',
    SelectedUnitOfMeasure: null,
    SelectedVariant: null,
    UnitOfMeasures: [
      {
        Id: 'EACH',
        Decimals: 0,
        Description: '',
        ItemId: '62',
        Price: 0,
        QtyPerUom: 1.0,
        ShortDescription: 'EACH',
      },
    ],
    UnitVolume: 0.0,
    UnitsPerParcel: 0.0,
    VariantsExt: [],
    VariantsRegistration: [],
  },
  {
    Id: '128032',
    AllowedToSell: true,
    BlockDiscount: false,
    BlockManualPriceChange: false,
    Blocked: false,
    Description: 'Alfa Clindamycin 300 Mg Injection',
    Details: '',
    Discount: 0,
    GrossWeight: 0.0,
    Images: [
      {
        Id: '',
        AvgColor: '',
        DisplayOrder: 0,
        Format: '',
        Image: '',
        ImgSize: {
          Height: 0,
          UseMinHorVerSize: false,
          Width: 0,
        },
        LoadFromFile: false,
        Location:
          'https://delmar-test.linkedgates.com/images/items/128032.JPEG',
        LocationType: 1,
      },
    ],
    IsDeleted: false,
    ItemAttributes: [],
    ItemCategoryCode: CategoryIDs.Medicine,
    ItemFamilyCode: 'MEDICINE',
    ItemPrice: 99.5,
    NewPrice: null,
    Price: '',
    Prices: [
      {
        Amount: '99.50',
        Amt: 99.5,
        ItemId: '128032',
        StoreId: 'WEB',
        UomId: 'EACH',
        VariantId: '',
      },
    ],
    ProductGroupId: 'ANTI-BIOTIC',
    SalesUomId: 'EACH',
    ScaleItem: false,
    SeasonCode: '',
    SelectedUnitOfMeasure: null,
    SelectedVariant: null,
    UnitOfMeasures: [
      {
        Id: 'AMP',
        Decimals: 0,
        Description: '',
        ItemId: '128032',
        Price: 0,
        QtyPerUom: 1.0,
        ShortDescription: 'AMP',
      },
      {
        Id: 'EACH',
        Decimals: 0,
        Description: '',
        ItemId: '128032',
        Price: 0,
        QtyPerUom: 5.0,
        ShortDescription: 'EACH',
      },
    ],
    UnitVolume: 0.0,
    UnitsPerParcel: 0.0,
    VariantsExt: [],
    VariantsRegistration: [],
  },
  {
    Id: '136229',
    AllowedToSell: true,
    BlockDiscount: false,
    BlockManualPriceChange: false,
    Blocked: false,
    Description: 'Alfacef 500Gm/100ml Vial',
    Details: '',
    Discount: 0,
    GrossWeight: 0.0,
    Images: [
      {
        Id: '',
        AvgColor: '',
        DisplayOrder: 0,
        Format: '',
        Image: '',
        ImgSize: {
          Height: 0,
          UseMinHorVerSize: false,
          Width: 0,
        },
        LoadFromFile: false,
        Location:
          'https://delmar-test.linkedgates.com/images/items/136229.JPEG',
        LocationType: 1,
      },
    ],
    IsDeleted: false,
    ItemAttributes: [],
    ItemCategoryCode: CategoryIDs.Medicine,
    ItemFamilyCode: 'MEDICINE',
    ItemPrice: 60.0,
    NewPrice: null,
    Price: '',
    Prices: [],
    ProductGroupId: 'ANTI-BIOTIC',
    SalesUomId: 'EACH',
    ScaleItem: false,
    SeasonCode: '',
    SelectedUnitOfMeasure: null,
    SelectedVariant: null,
    UnitOfMeasures: [
      {
        Id: 'EACH',
        Decimals: 0,
        Description: '',
        ItemId: '136229',
        Price: 0,
        QtyPerUom: 1.0,
        ShortDescription: 'EACH',
      },
    ],
    UnitVolume: 0.0,
    UnitsPerParcel: 0.0,
    VariantsExt: [],
    VariantsRegistration: [],
  },
  {
    Id: '125289',
    AllowedToSell: true,
    BlockDiscount: false,
    BlockManualPriceChange: false,
    Blocked: false,
    Description: 'Alfacef 750 Mg  5 Tab ',
    Details: '',
    Discount: 0,
    GrossWeight: 0.0,
    Images: [
      {
        Id: '',
        AvgColor: '',
        DisplayOrder: 0,
        Format: '',
        Image: '',
        ImgSize: {
          Height: 0,
          UseMinHorVerSize: false,
          Width: 0,
        },
        LoadFromFile: false,
        Location:
          'https://delmar-test.linkedgates.com/images/items/125289.JPEG',
        LocationType: 1,
      },
    ],
    IsDeleted: false,
    ItemAttributes: [],
    ItemCategoryCode: CategoryIDs.Medicine,
    ItemFamilyCode: 'MEDICINE',
    ItemPrice: 60.0,
    NewPrice: null,
    Price: '',
    Prices: [
      {
        Amount: '60.00',
        Amt: 60.0,
        ItemId: '125289',
        StoreId: 'WEB',
        UomId: 'EACH',
        VariantId: '',
      },
    ],
    ProductGroupId: 'ANTI-BIOTIC',
    SalesUomId: 'EACH',
    ScaleItem: false,
    SeasonCode: '',
    SelectedUnitOfMeasure: null,
    SelectedVariant: null,
    UnitOfMeasures: [
      {
        Id: 'EACH',
        Decimals: 0,
        Description: '',
        ItemId: '125289',
        Price: 0,
        QtyPerUom: 1.0,
        ShortDescription: 'EACH',
      },
    ],
    UnitVolume: 0.0,
    UnitsPerParcel: 0.0,
    VariantsExt: [],
    VariantsRegistration: [],
  },
  {
    Id: '101149',
    AllowedToSell: true,
    BlockDiscount: false,
    BlockManualPriceChange: false,
    Blocked: false,
    Description: 'Amikacin 500 Gm 1 Vial Im Iv 2 ML',
    Details: '',
    Discount: 0,
    GrossWeight: 0.0,
    Images: [
      {
        Id: '',
        AvgColor: '',
        DisplayOrder: 0,
        Format: '',
        Image: '',
        ImgSize: {
          Height: 0,
          UseMinHorVerSize: false,
          Width: 0,
        },
        LoadFromFile: false,
        Location:
          'https://delmar-test.linkedgates.com/images/items/101149.JPEG',
        LocationType: 1,
      },
    ],
    IsDeleted: false,
    ItemAttributes: [],
    ItemCategoryCode: CategoryIDs.Medicine,
    ItemFamilyCode: 'MEDICINE',
    ItemPrice: 16.0,
    NewPrice: null,
    Price: '',
    Prices: [
      {
        Amount: '16.00',
        Amt: 16.0,
        ItemId: '101149',
        StoreId: 'WEB',
        UomId: 'EACH',
        VariantId: '',
      },
    ],
    ProductGroupId: 'ANTI-BIOTIC',
    SalesUomId: 'EACH',
    ScaleItem: false,
    SeasonCode: '',
    SelectedUnitOfMeasure: null,
    SelectedVariant: null,
    UnitOfMeasures: [
      {
        Id: 'EACH',
        Decimals: 0,
        Description: '',
        ItemId: '101149',
        Price: 0,
        QtyPerUom: 1.0,
        ShortDescription: 'EACH',
      },
    ],
    UnitVolume: 0.0,
    UnitsPerParcel: 0.0,
    VariantsExt: [],
    VariantsRegistration: [],
  },
  {
    Id: '125192',
    AllowedToSell: true,
    BlockDiscount: false,
    BlockManualPriceChange: false,
    Blocked: false,
    Description: 'Amikacin Lotion Spray 100 ML',
    Details: '',
    Discount: 0,
    GrossWeight: 0.0,
    Images: [
      {
        Id: '',
        AvgColor: '',
        DisplayOrder: 0,
        Format: '',
        Image: '',
        ImgSize: {
          Height: 0,
          UseMinHorVerSize: false,
          Width: 0,
        },
        LoadFromFile: false,
        Location:
          'https://delmar-test.linkedgates.com/images/items/125192.JPEG',
        LocationType: 1,
      },
    ],
    IsDeleted: false,
    ItemAttributes: [],
    ItemCategoryCode: CategoryIDs.Medicine,
    ItemFamilyCode: 'MEDICINE',
    ItemPrice: 27.0,
    NewPrice: null,
    Price: '',
    Prices: [
      {
        Amount: '27.00',
        Amt: 27.0,
        ItemId: '125192',
        StoreId: 'WEB',
        UomId: 'EACH',
        VariantId: '',
      },
    ],
    ProductGroupId: 'ANTI-BIOTIC',
    SalesUomId: 'EACH',
    ScaleItem: false,
    SeasonCode: '',
    SelectedUnitOfMeasure: null,
    SelectedVariant: null,
    UnitOfMeasures: [
      {
        Id: 'EACH',
        Decimals: 0,
        Description: '',
        ItemId: '125192',
        Price: 0,
        QtyPerUom: 1.0,
        ShortDescription: 'EACH',
      },
    ],
    UnitVolume: 0.0,
    UnitsPerParcel: 0.0,
    VariantsExt: [],
    VariantsRegistration: [],
  },
  {
    Id: '119642',
    AllowedToSell: true,
    BlockDiscount: false,
    BlockManualPriceChange: false,
    Blocked: false,
    Description: 'Amoclawin 457 Mg/5 Mlsusp 60Ml ',
    Details: '',
    Discount: 0,
    GrossWeight: 0.0,
    Images: [
      {
        Id: '',
        AvgColor: '',
        DisplayOrder: 0,
        Format: '',
        Image: '',
        ImgSize: {
          Height: 0,
          UseMinHorVerSize: false,
          Width: 0,
        },
        LoadFromFile: false,
        Location:
          'https://delmar-test.linkedgates.com/images/items/119642.JPEG',
        LocationType: 1,
      },
    ],
    IsDeleted: false,
    ItemAttributes: [],
    ItemCategoryCode: CategoryIDs.Medicine,
    ItemFamilyCode: 'MEDICINE',
    ItemPrice: 22.5,
    NewPrice: null,
    Price: '',
    Prices: [
      {
        Amount: '22.50',
        Amt: 22.5,
        ItemId: '119642',
        StoreId: 'WEB',
        UomId: 'EACH',
        VariantId: '',
      },
    ],
    ProductGroupId: 'ANTI-BIOTIC',
    SalesUomId: 'EACH',
    ScaleItem: false,
    SeasonCode: '',
    SelectedUnitOfMeasure: null,
    SelectedVariant: null,
    UnitOfMeasures: [
      {
        Id: 'EACH',
        Decimals: 0,
        Description: '',
        ItemId: '119642',
        Price: 0,
        QtyPerUom: 1.0,
        ShortDescription: 'EACH',
      },
    ],
    UnitVolume: 0.0,
    UnitsPerParcel: 0.0,
    VariantsExt: [],
    VariantsRegistration: [],
  },
  {
    Id: '95513',
    AllowedToSell: true,
    BlockDiscount: false,
    BlockManualPriceChange: false,
    Blocked: false,
    Description: 'Amofluxin 1G(500/500) 12 Cap',
    Details: '',
    Discount: 0,
    GrossWeight: 0.0,
    Images: [
      {
        Id: '',
        AvgColor: '',
        DisplayOrder: 0,
        Format: '',
        Image: '',
        ImgSize: {
          Height: 0,
          UseMinHorVerSize: false,
          Width: 0,
        },
        LoadFromFile: false,
        Location: 'https://delmar-test.linkedgates.com/images/items/95513.JPEG',
        LocationType: 1,
      },
    ],
    IsDeleted: false,
    ItemAttributes: [],
    ItemCategoryCode: CategoryIDs.Medicine,
    ItemFamilyCode: 'MEDICINE',
    ItemPrice: 14.4,
    NewPrice: null,
    Price: '',
    Prices: [
      {
        Amount: '14.40',
        Amt: 14.4,
        ItemId: '95513',
        StoreId: 'WEB',
        UomId: 'EACH',
        VariantId: '',
      },
    ],
    ProductGroupId: 'ANTI-BIOTIC',
    SalesUomId: 'EACH',
    ScaleItem: false,
    SeasonCode: '',
    SelectedUnitOfMeasure: null,
    SelectedVariant: null,
    UnitOfMeasures: [
      {
        Id: 'EACH',
        Decimals: 0,
        Description: '',
        ItemId: '95513',
        Price: 0,
        QtyPerUom: 2.0,
        ShortDescription: 'EACH',
      },
      {
        Id: 'STRIP',
        Decimals: 0,
        Description: '',
        ItemId: '95513',
        Price: 0,
        QtyPerUom: 1.0,
        ShortDescription: 'STRIP',
      },
    ],
    UnitVolume: 0.0,
    UnitsPerParcel: 0.0,
    VariantsExt: [],
    VariantsRegistration: [],
  },
  {
    Id: '3658',
    AllowedToSell: true,
    BlockDiscount: false,
    BlockManualPriceChange: false,
    Blocked: false,
    Description: 'Amoxil Forte 250 Mg 100 ML Syrup 5 ML',
    Details: '',
    Discount: 0,
    GrossWeight: 0.0,
    Images: [
      {
        Id: '',
        AvgColor: '',
        DisplayOrder: 0,
        Format: '',
        Image: '',
        ImgSize: {
          Height: 0,
          UseMinHorVerSize: false,
          Width: 0,
        },
        LoadFromFile: false,
        Location: 'https://delmar-test.linkedgates.com/images/items/3658.JPEG',
        LocationType: 1,
      },
    ],
    IsDeleted: false,
    ItemAttributes: [],
    ItemCategoryCode: CategoryIDs.Medicine,
    ItemFamilyCode: 'MEDICINE',
    ItemPrice: 11.0,
    NewPrice: null,
    Price: '',
    Prices: [
      {
        Amount: '11.00',
        Amt: 11.0,
        ItemId: '3658',
        StoreId: 'WEB',
        UomId: 'EACH',
        VariantId: '',
      },
    ],
    ProductGroupId: 'ANTI-BIOTIC',
    SalesUomId: 'EACH',
    ScaleItem: false,
    SeasonCode: '',
    SelectedUnitOfMeasure: null,
    SelectedVariant: null,
    UnitOfMeasures: [
      {
        Id: 'EACH',
        Decimals: 0,
        Description: '',
        ItemId: '3658',
        Price: 0,
        QtyPerUom: 1.0,
        ShortDescription: 'EACH',
      },
    ],
    UnitVolume: 0.0,
    UnitsPerParcel: 0.0,
    VariantsExt: [],
    VariantsRegistration: [],
  },
];
